title = "Repo secret scan rules"

# Enable default rules
[extend]
useDefault = true

# Custom allowlist for test data or fake tokens
[allowlist]
description = "Allow common false positives"
paths = [
  '''^tests?/''',
  '''^fixtures?/'''
]
